spring.application.name=EurekaServer
server.port=8761

# Disable self-registration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Default Zone URL (Ensure the trailing slash is there)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/ 