spring.application.name=apigateway
server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#spring.cloud.gateway.discovery.locator.enabled=false

#spring.cloud.gateway.routes[0].id=student-service-route
#spring.cloud.gateway.routes[0].uri=lb://student-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/student/**


#spring.cloud.gateway.routes[1].id=address-service-route
#spring.cloud.gateway.routes[1].uri=lb://address-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/address/**
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
